In [2]:
import pandas as pd
import requests

In [4]:
response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1")

In [8]:
df = pd.DataFrame(response.json()["results"])

In [13]:
df = df[["id", "title", "overview", "release_date", "popularity"]]

In [14]:
df

,id,title,overview,release_date,popularity
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,38.3467
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,34.9917
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,19.4661
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,19.3480
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,17.6774
5,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,5.6660
6,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,27.7621
7,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,40.7707
8,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,16.3979
9,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,19.4247
10,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,25.7258
11,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,26.4186
12,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,23.3183
13,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,22.9310
14,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,51.9612
15,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,18.9398
16,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,25.9672
17,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,19.8633
18,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,9.2682
19,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.0125

In [15]:
new_df = pd.DataFrame()

In [16]:
new_df

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1, 429):
    response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}", format(i))
    temp_df = pd.DataFrame(response.json()["results"])[["id", "title", "overview", "release_date", "popularity"]]
    new_df = new_df.append(temp_df, ignore_index=True)

In [ ]:
new_df