In [11]:
import pandas as pd
import requests

In [12]:
response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1")

In [13]:
df = pd.DataFrame(response.json()["results"])

In [14]:
df = df[["id", "title", "overview", "release_date", "popularity"]]

In [ ]:
df

In [20]:
res = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1")
pd.DataFrame(res.json()["results"])

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,47.7967,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.716,29890
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",37.6783,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.688,22569
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,22.0890,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.571,13669
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,21.8629,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.566,17191
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,21.1427,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.556,9807
5,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",7.3812,/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg,2023-09-21,¿Quieres ser mi hijo?,False,8.543,301
6,False,/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",29.3079,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.534,18047
7,False,/dqK9Hag1054tghRQSqLSfrkvQnA.jpg,"[28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,36.2248,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.527,35309
8,False,/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",17.4475,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.500,4564
9,False,/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,21.3566,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,The Green Mile,False,8.505,18938
10,False,/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",28.9129,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.493,20248
11,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,27.6750,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,The Lord of the Rings: The Return of the King,False,8.494,26145
12,False,/96hiUXEuYsu4tcnvlaY8tEMFM0m.jpg,"[53, 80, 35]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",27.6291,/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg,1994-09-10,Pulp Fiction,False,8.486,29811
13,False,/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,23.1130,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.479,12341
14,False,/2ssWTSVklAEc98frZUQhgtGHx7s.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,59.3667,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,Interstellar,False,8.468,39079
15,False,/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,21.2763,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-23,"The Good, the Bad and the Ugly",False,8.500,9473
16,False,/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,28.2881,/saHP97rTPS5eLmrLQEcANmKrsFl.jpg,1994-06-23,Forrest Gump,False,8.463,29355
17,False,/gILte6Zd7m1YneIr6MVhh30S9pr.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",25.4363,/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg,1990-09-12,GoodFellas,False,8.452,14094
18,False,/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,9.7958,/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg,1954-04-26,Seven Samurai,False,8.451,4136
19,False,/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.0127,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.444,6398

In [6]:
new_df = pd.DataFrame()

In [7]:
new_df

Empty DataFrame
Columns: []
Index: []

In [ ]:
dfs = []

for i in range(1, 429):
    response = requests.get(
        f"https://api.themoviedb.org/3/movie/top_rated?api_key=YOUR_API_KEY&language=en-US&page={i}"
    )

    data = response.json()

    if "results" in data:
        temp_df = pd.DataFrame(data["results"])
        temp_df = temp_df[["id","title","overview","release_date","popularity"]]
        dfs.append(temp_df)
    else:
        print(f"Error on page {i}:", data)

new_df = pd.concat(dfs, ignore_index=True)

In [9]:
new_df

Empty DataFrame
Columns: []
Index: []